fixed issue on insufficient available space when upgrading packages

diff --git a/fruit-update.in b/fruit-update.in
--- a/fruit-update.in
+++ b/fruit-update.in
@@ -7,7 +7,7 @@ else
 	non_active="/dev/mmcblk0p2"
 fi
 
-non_active_dir=/media/non-active
+non_active_dir=/media/root-bak
 flag_dir=/media/mmcblk0p1
 flag_file="$flag_dir/$(echo "$non_active" | sed 's/\//./g').dirty"
 
@@ -47,19 +47,53 @@ umount_non_active() {
 }
 
 apply_update() {
-	apk -q --root $non_active_dir update \
-		1>/tmp/.fruit-update.apk-update.stdout \
-		2>/tmp/.fruit-update.apk-update.stderr
-	apk --root $non_active_dir --purge --wait 1200 upgrade \
-		1>/tmp/.fruit-update.apk-upgrade.stdout \
-		2>/tmp/.fruit-update.apk-upgrade.stderr
-	local ret=$?
-	return $ret
+  local tmp=/media/root-tmp
+  local update=/media/root-update
+  local diff=$(mktemp)
+  local ret=0
+
+  mkdir -p $tmp $update \
+	  && mount -t tmpfs root-tmpfs $tmp \
+	  && mkdir -p $tmp/root $tmp/work \
+	  && mount -t overlay \
+        -o lowerdir=$non_active_dir,upperdir=$tmp/root,workdir=$tmp/work \
+		    overlayfs $update \
+    && apk -q --root $update update \
+        1>/tmp/.fruit-update.apk-update.stdout \
+        2>/tmp/.fruit-update.apk-update.stderr \
+    && apk --root $update --purge --wait 1200 upgrade \
+        1>/tmp/.fruit-update.apk-upgrade.stdout \
+        2>/tmp/.fruit-update.apk-upgrade.stderr \
+
+  ret=$((ret + $?))
+  if [ $ret -eq 0 ]; then
+    diff -rq --no-dereference $update $non_active_dir > $diff
+    grep " differ$" $diff | while read line; do
+      src=$(echo "$line" | cut -d' ' -f2)
+		  dst=$(echo "$line" | cut -d' ' -f4)
+		  echo "Copying $src to $dst"
+		  cp -a "$src" "$dst"
+		  ret=$((ret + $?))
+	  done
+	  grep "Only on ${root}:" $diff | while read line; do
+		  file=$(echo "$line" | cut -d' ' -f4)
+		  echo "Deleting $file"
+		  rm -f "$file"
+		  ret=$((ret + $?))
+	  done
+  else
+	  echo "'apk upgrade' failed"
+  fi
+  umount -f $update
+  umount -f $tmp
+  rm -f $diff
+  return $ret
 }
 
 recover_non_active() {
 	logger -st fruit "Recovering: cloning $active to $non_active"
-	dd if=$active of=$non_active 2>/dev/null
+	dd if=$active of=$non_active 2>/dev/null \
+	  && mark_clean $non_active
 	local ret=$?
 	[ $ret -eq 0 ] && \
 		logger -st fruit "Recovered $non_active" || \
