fixed typos; added setup_sshd()

diff --git a/fruit-deploy.in b/fruit-deploy.in
--- a/fruit-deploy.in
+++ b/fruit-deploy.in
@@ -43,7 +43,7 @@ download_ssh_public_key() {
 	local target="/root/.ssh/authorized_keys"
 	download_resource "ssh_key" ${target}
 	[ $? -ne 0 ] \
-		&& logger -st fruit "WARNING: Failed to download SSH Public Key from server"
+		&& logger -st fruit "WARNING: Failed to download SSH Public Key from server" \
 		&& return 0
 	chmod 0700 $(dirname "$target") && chmod 0640 ${target}
 	return $?
@@ -57,10 +57,10 @@ setup_openvpn() {
 	local target="/run/openvpn.tar.gz"
 	download_resource "openvpn" ${target}
 	[ $? -ne 0 ] \
-		&& logget -st fruit "WARNING: Failed to download OpenVPN config from server"
+		&& logget -st fruit "WARNING: Failed to download OpenVPN config from server" \
 		&& return 1
 	tar -C /etc/openvpn/ -xzf ${target} \
-		&& rc-update add openvpn default
+		&& rc-update add openvpn default \
 		&& rc-service openvpn start
 	return $?
 }
@@ -339,6 +339,13 @@ setup_docker() {
 	return $ret
 }
 
+setup_sshd() {
+	local config=/etc/ssh/sshd_config
+	sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin prohibit-password/g' ${config} \
+		&& sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/g' ${config}
+	return $?
+}
+
 ##### main #####
 
 case "$(rc-status -r)" in
@@ -347,6 +354,7 @@ case "$(rc-status -r)" in
 		setup_hostname
 		setup_network
 		setup_monitor
+		setup_sshd
 		;;
 	default)
 		download_config_server_to_run
