restored lock-file in fruit-config

diff --git a/fruit-config.in b/fruit-config.in
--- a/fruit-config.in
+++ b/fruit-config.in
@@ -637,11 +637,13 @@ enable_nat() {
 
 ##### main #####
 
-pidof fruit-config 1>/dev/null 2>/dev/null
-if [ $? -eq 0 ]; then
-	echo "Exiting because another instance of fruit-config is running."
-	exit 0
-fi
+lockfile="/run/$(basename $0).lock"
+[ -f lockfile ] && [ "$(find ${lockfile} -mmin -30 2>/dev/null)" = "" ] \
+		&& logger -st fruit "ERROR: Lock file ${lockfile} exists" \
+		&& exit 1
+
+rm -f ${lockfile}
+touch ${lockfile}
 
 # random sleep between 0-299 seconds
 [ "$1" = "cron" ] && sleep $(shuf -i 0-299 -n 1)
@@ -682,5 +684,7 @@ case "$(rc-status -r)" in
 		true
 		;;
 esac
+
+rm -f ${lockfile}
 
 exit 0
